### ISSUE TITLE
我的汉化器窗口一直都不居中

### ISSUE THREAD

**Issue by MachineSpirit** [XhYde/PS2CN-Launcher#1]
就是第一次打开的时候不小心点到鼠标了,窗口还没加载全的时候被我拖到右下角了,然后后面就一直都是默认弹到右下角的位置,重新解压过文件也一样.不晓得怎么搞.

**Comment by XhYde** [comment]
汉化器窗口位置每次打开都是固定的，是在游戏登录器的右下角。
如果电脑屏幕分辨率低的话，汉化器窗口就会顶到右下角。
只要汉化器窗口没超出屏幕都属正常。

**Comment by MachineSpirit** [comment]
如果是固定的话能不能把窗口抬高一点,我的 启动登录器 的按钮被任务栏挡住了.
主要是以前用我另一台笔记本的时候也没这问题啊.
感觉挺奇怪的,也不知道是不是我现在的笔记本装的win10的问题
15.6寸笔记本 1920*1080的分辨率

**Comment by MachineSpirit** [comment]
看了一下好像是被你放在右下方了...................

位置是对的,就是我放大了一下图标,所以窗口变大了,然后按钮就被任务栏挡住了.
如果以前也是这样的话,那以前应该就是没有放大图标,所以之前的位置没什么问题.

既然获取到了分辨率咋不居中呢..........
@_@ 我还一直以为哪里出了什么问题.

不过还是感谢一下大佬,这么多行代码.还有汉化的文件.还有那么多的注释.
