### ISSUE TITLE
感谢你们的工作

### ISSUE THREAD

**Issue by cyber-tao** [XhYde/PS2CN-Launcher#2]
上大学的时候非常喜欢《星际Online》，是我除了WOW之外最爱的游戏了。
现在工作十多年，又回想起那时的快乐了，找到了二代，但发现国服没有了，只有美服。
而你们让国内的玩家可以舒服地玩美服，没有语言障碍，非常感谢！加油！

**Comment by wyy007cn** [comment]
感谢分享，期待已久，祝楼主大吉大利、全家幸福、身体安康、四季发财。

**Comment by naizut** [comment]
老哥辛苦了 Star为敬

**Comment by feifei200x** [comment]
转到github感觉稳妥了，不会忽然找不到组织了
